### ISSUE TITLE
Un/intentional feeding?

### ISSUE THREAD

**Issue by acheeseye** [acheeseye/ai-playing-checkers#10]
Through replays of `best_of_GEN9`, it often seems like one player if intentionally feeding the other. I suspect this is either due to some negative values being translated incorrectly or simply not enough generations (along with not enough ply). I would like to implement alpha-beta pruning before upping the ply count for training, but I'm going to try with 4 ply for now anyway.

**Comment by acheeseye** [comment]
Perhaps, since we piece count was not fed into the network and done by `min_max_search`, the network is not coming up with the piece count mentality.

**Comment by woodchip-dev** [comment]
I'll have to take a look at those replays. Is it possible that when the `min_max_search` is used, it's always the same player that's on max and the other on min regardless of whose turn it is? I would hope it's not learning to lose.
Also, I'm working on alpha-beta pruning. I may not have it ready today though.

**Comment by acheeseye** [comment]
👍

That is a possibility yes since we've set up hardcoded positivity/negativity for each side. I will provide some GEN9 results for the 4ply network and see what happens.

**Comment by acheeseye** [comment]
This has been resolved with `min_max_search`/`alpha_beta` functions not internally applying play modifiers (such as `if(board.get_Player() == _BLACK_)`), as it is resolved externally with `NeuralNetwork_PERF`'s `m_player_modifier`. One or the other needs to be chosen.

**Comment by acheeseye** [comment]
Chosen that evaluation functions will be general purpose.
