### ISSUE TITLE
Two AIs

### ISSUE THREAD

**Issue by acheeseye** [acheeseye/ai-playing-checkers#5]
Two AIs results in gameplay until either side has only one piece left. This apparently maks `m_possible_moves_list == 0`, thus triggering the `if(board.is_over())` condition and ending the game prematurely then follows with a crash.

**Comment by woodchip-dev** [comment]
Found a solution for this, see Version 4.3 notes. Now, if either AI has no moves left, it will not attempt to make a move for the AI that has no moves left.
